### ISSUE TITLE
Best way to create the images?

### ISSUE THREAD

**Issue by dirkk0** [richtr/threeVR#7]
Hi,

  I know that this is out of scope of this project but - do you know a 'best way' to create the 6 images used by it?

Thanks,
  Dirk

**Comment by dongwenxiao** [comment]
So, do you get zhe best way ? 
I hope zhe anwser,too...

Thanks,
victor

**Comment by richtr** [comment]
The six images used are part of a [cube map](https://en.wikipedia.org/wiki/Cube_mapping).

The best way to obtain such images is to first capture an equirectangular panorama using a 360 degree camera. You can then project this equirectangular image on to a sphere (e.g. like [this](https://mrdoob.github.io/three.js/examples/webgl_panorama_equirectangular.html)) or you could convert it to a cube map using e.g. [this mechanism](https://stackoverflow.com/questions/29678510/convert-21-equirectangular-panorama-to-cube-map) and project each of the 6 images on to a sphere as in the demo provided in this library.

If you do not want to, or can not, use specialist equipment to capture images then you should also check out [Google Photo Sphere](http://www.androidcentral.com/photo-sphere) that produces equirectangular panorama images on both Android and iOS devices.
